import React, { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Camera, VideoOff } from 'lucide-react';
import { CameraPositionId, SportType } from '../types';
import { CAMERA_POSITIONS, drawSimulatedAngleFootage } from '../utils/mockFootage';
interface CameraViewProps {positionId:CameraPositionId;sport:SportType;onExit:()=>void;isTriggered:boolean;onSelectPosition:(id:CameraPositionId)=>void}
export function CameraView({positionId,sport,onExit,onSelectPosition}:CameraViewProps){
 const [real,setReal]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState<string|null>(null);
 const video=useRef<HTMLVideoElement>(null),canvas=useRef<HTMLCanvasElement>(null),stream=useRef<MediaStream|null>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;stream.current?.getTracks().forEach(track=>track.stop());};},[]);
 useEffect(()=>{if(real&&video.current){video.current.srcObject=stream.current;video.current.play().catch(()=>setError('Toque no vídeo para iniciar a visualização.'));}},[real]);
 useEffect(()=>{if(real)return;let frame:number;const start=performance.now();const render=(now:number)=>{const ctx=canvas.current?.getContext('2d');if(ctx&&canvas.current)drawSimulatedAngleFootage(ctx,960,540,positionId,sport,((now-start)/1000)%40);frame=requestAnimationFrame(render);};frame=requestAnimationFrame(render);return()=>cancelAnimationFrame(frame);},[real,positionId,sport]);
 const start=async()=>{setPending(true);setError(null);try{if(!navigator.mediaDevices?.getUserMedia)throw Error('unsupported');const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1280},height:{ideal:720}},audio:false});if(!mounted.current){media.getTracks().forEach(track=>track.stop());return;}stream.current=media;setReal(true);}catch{if(mounted.current)setError('Não foi possível abrir a webcam. Confira a permissão de câmera do navegador e tente novamente.');}finally{if(mounted.current)setPending(false);}};
 const stop=()=>{stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;setReal(false);};
 return <section className="web-camera"><button className="back-link" onClick={onExit}><ArrowLeft size={18}/>Voltar</button><h1>Seu ponto de vista.</h1><p>{real?'Prévia da webcam deste computador':'Câmera simulada'}</p><div className="web-camera-video">{real?<video ref={video} autoPlay muted playsInline controls aria-label="Prévia da webcam"/>:<canvas ref={canvas} width={960} height={540} aria-label="Animação de vôlei demonstrativa"/>}</div><label>Posição da câmera<select value={positionId} onChange={e=>onSelectPosition(e.target.value as CameraPositionId)}>{Object.entries(CAMERA_POSITIONS).map(([id,pos])=><option value={id} key={id}>{pos.label}</option>)}</select></label>{error&&<p role="alert" className="camera-error">{error}</p>}<button className="primary-button" onClick={real?stop:start} disabled={pending}>{real?<><VideoOff size={20}/>Desligar webcam</>:<><Camera size={20}/>{pending?'Abrindo câmera…':'Usar webcam real'}</>}</button><p className="camera-explanation">A versão web mostra o enquadramento, mas não grava nem conecta outros aparelhos. A captura e o replay reais ficam no aplicativo Android e iPhone.</p></section>;
}
